[window]
dynamic_title = true

[window.padding]
x = 4
y = 4

[window.dimensions]
columns = 80
lines = 24

[env]
LANG = "en_US.UTF-8"
LC_ALL = "en_US.UTF-8"
TERM = "xterm-256color"

[font]
size = 18

[font.normal]
family = "IosevkaTerm Nerd Font"
style = "Regular"

[font.bold]
family = "IosevkaTerm Nerd Font"
style = "Bold"

[font.italic]
family = "IosevkaTerm Nerd Font"
style = "Italic"

[font.bold_italic]
family = "IosevkaTerm Nerd Font"
style = "Bold Italic"

[colors]
draw_bold_text_with_bright_colors = true

[scrolling]
history = 0

[general]
import = [ "~/.config/alacritty/themes/themes/solarized_light.toml" ]
